name: spokes
version: 0.5.2
author: Billy Welch <billywelch@gmail.com>
description: A Django-inspired framework
homepage: https://github.com/billysometimes/spokes
dependencies:
  logging_handlers: any
dev_dependencies:
  args: '>=0.10.0+1 <0.11.0'
